### PR TITLE
add `CryoPoseDataFrame` type alias

### PR DESCRIPTION
**Pull request by alisterburt**

### CODE REVIEW

**Comment by alisterburt** [comment]
cc @brisvag

**Comment by brisvag** [comment]
What is this for exaclt? It just seems more verbose than using `pd.DataFrame`, and it does not add anything to it as far as I can tell... Not familiar with type aliases though!

**Comment by alisterburt** [comment]
the idea was that I could indicate in other packages that I'm returning something which conforms to this API, rather than just a dataframe - just adds some semantics, what do you think?

**Comment by brisvag** [comment]
I guess it doesn't hurt! But it makes me wonder if we could have a type that statically checks dataframe columns... I supposed that wouldn't be static typing anymore tho :P

**Pull request merged**
